apiVersion: apps/v1
kind: Deployment
metadata:
  name: vattenlada-api
  labels:
    app: vattenlada-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vattenlada-api
  template:
    metadata:
      labels:
        app: vattenlada-api
    spec:
      # Specify host network as true, or we won't be able to access MongoDB cloud
      hostNetwork: true
      containers:
      - name: vattenlada-api
        image: mfarmer5102/vattenlada-api:latest
        env:
        - name: MONGODB_URI
          value: ''
        ports:
        # Port exposed by the Docker container
        - containerPort: 9010

---

apiVersion: v1
kind: Service
metadata:
  name: vattenlada-api-service
spec:
  type: NodePort
  selector:
    app: vattenlada-api
  ports:
    - protocol: TCP
      # Port exposed by the Docker container
      port: 9010
      # Port exposed by the Docker container
      targetPort: 9010
      # Port on host machine where it should be accessible
      nodePort: 30803